### ISSUE TITLE
TypeError when importing from `'typescript'` in file

### ISSUE THREAD

**Issue by qlonik** [alexgorbatchev/eslint-import-resolver-typescript#47]
Whenever I have imports from `'typescript'` module, I get type error: `TypeError: Cannot read property 'type' of null`. I'm not sure if it is caused by this package or is coming from somewhere else. However, when I comment out the line `'import/resolver': { typescript: { alwaysTryTypes: true } },` in `.eslintrc.js` file, then the file gets properly linted.

I created a small reproduction here: https://github.com/qlonik/eslint-import-resolver-typescript-repro

**Comment by JounQin** [comment]
The error message is as following:

```log
TypeError: Cannot read property 'type' of null
Occurred while linting /workspace/eslint-import-resolver-typescript-repro/src.ts:1
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:569:30
    at Array.forEach (<anonymous>)
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:565:32
    at Array.forEach (<anonymous>)
    at /workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:563:19
    at Array.forEach (<anonymous>)
    at Function.ExportMap.parse (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:477:12)
    at Function.ExportMap.for (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:361:25)
    at Function.ExportMap.get (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/ExportMap.js:316:23)
    at processBodyStatement (/workspace/eslint-import-resolver-typescript-repro/node_modules/eslint-plugin-import/lib/rules/namespace.js:67:47)
```

As you can see it comes from `eslint-plugin-import`, and if you lock `"eslint-plugin-import": "~2.18.2"`, it will just work.

So please post the issue to [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) instead, and as I know it should be an issue of parsing `export {}`.

**Comment by qlonik** [comment]
Thank you for filing it upstream and resolving it with the maintainer of the upstream package. I really appreciate it :)
